services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - API_URL=${API_URL}
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true


  backend:
    build:
      context: ./backend
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - redis
    environment:
      - REDIS_URL=${REDIS_URL}
      - FRONTEND_URL=${FRONTEND_URL}

  redis:
    image: redis:7
    ports:
      - "6379:6379"